[project]
name = "torrent-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.10",
    "bitstring>=4.3.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
